---------- Khai báo khóa chính ----------
ALTER TABLE DAILY
ADD CONSTRAINT PK_DL PRIMARY KEY (MaDaiLy)

ALTER TABLE LOAIDAILY
ADD CONSTRAINT PK_LDL PRIMARY KEY (MaLoaiDaiLy)

ALTER TABLE QUAN
ADD CONSTRAINT PK_QUAN PRIMARY KEY (MaQuan)

ALTER TABLE PHIEUNHAPHANG
ADD CONSTRAINT PK_PNH PRIMARY KEY (MaPhieuNhap)

ALTER TABLE CT_PNH
ADD CONSTRAINT PK_CT_PNH PRIMARY KEY (MaPhieuNhap, MaMH)

ALTER TABLE MATHANG
ADD CONSTRAINT PK_MH PRIMARY KEY (MaMH)

ALTER TABLE DVT
ADD CONSTRAINT PK_DVT PRIMARY KEY (MaDVT)

ALTER TABLE PHIEUXUATHANG
ADD CONSTRAINT PK_XE PRIMARY KEY (MaPhieuXuat)

ALTER TABLE CT_PXH
ADD CONSTRAINT PK_CT_PXH PRIMARY KEY (MaPhieuXuat, MaMH)

ALTER TABLE PHIEUTHUTIEN
ADD CONSTRAINT PK_PTT PRIMARY KEY (MaPhieuThuTien)

ALTER TABLE BAOCAODOANHSO
ADD CONSTRAINT PK_BCDS PRIMARY KEY (MaBCDS)

ALTER TABLE CT_BCDS
ADD CONSTRAINT PK_CT_BCDS PRIMARY KEY (MaBCDS, MaDaiLy)

ALTER TABLE BAOCAOCONGNO
ADD CONSTRAINT PK_BCCN PRIMARY KEY (MaBCCN)

ALTER TABLE CT_BCCN
ADD CONSTRAINT PK_CT_BCCN PRIMARY KEY (MaBCCN, MaDaiLy)

---------- Khai báo khóa ngoại ----------
ALTER TABLE DAILY
ADD CONSTRAINT FK_DL_LDL FOREIGN KEY (MaLoaiDaiLy) REFERENCES LOAIDAILY(MaLoaiDaiLy),
    CONSTRAINT FK_DL_QUAN FOREIGN KEY (MaQuan) REFERENCES QUAN(MaQuan)

ALTER TABLE CT_PNH
ADD CONSTRAINT FK_CTPNH_PNH FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEUNHAPHANG(MaPhieuNhap),
    CONSTRAINT FK_MaMH FOREIGN KEY (MaMH) REFERENCES MATHANG(MaMH)

ALTER TABLE MATHANG
ADD CONSTRAINT FK_MH_DVT FOREIGN KEY (MaDVT) REFERENCES DVT(MaDVT)

ALTER TABLE PHIEUXUATHANG
ADD CONSTRAINT FK_PXH_DL FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy)

ALTER TABLE CT_PXH
ADD CONSTRAINT FK_CTPXH_MH FOREIGN KEY (MaMH) REFERENCES MATHANG(MaMH),
    CONSTRAINT FK_CTPXH_PXH FOREIGN KEY (MaPhieuXuat) REFERENCES PHIEUXUATHANG(MaPhieuXuat)

ALTER TABLE PHIEUTHUTIEN
ADD CONSTRAINT FK_PTT_DL FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy)

ALTER TABLE CT_BCDS
ADD CONSTRAINT FK_CTBCDS_DL FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy),
    CONSTRAINT FK_CTBCDS_BCDS FOREIGN KEY (MaBCDS) REFERENCES BAOCAODOANHSO(MaBCDS)

ALTER TABLE CT_BCCN
ADD CONSTRAINT FK_CTBCCN_DL FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy),
    CONSTRAINT FK_CTBCCN_BCCN FOREIGN KEY (MaBCCN) REFERENCES BAOCAOCONGNO(MaBCCN)

